### ISSUE TITLE
Malwarwe : MultiMiner getting tagged as Malware on VirusTotal.com 

### ISSUE THREAD

**Issue by lihas** [nwoolls/MultiMiner#260] opened 2017-02-06 09:25 UTC
MultiMiner-4.0.4.exe is getting tagged as Malware on Virustotal. [See this link  - https://www.virustotal.com/en/file/b006e5565dbe2fdea9bc7afbaf0599c8985cdc9e31b74ace828ca296f7040291/analysis/1486372607/](https://www.virustotal.com/en/file/b006e5565dbe2fdea9bc7afbaf0599c8985cdc9e31b74ace828ca296f7040291/analysis/1486372607/)

**Comment by nwoolls** [comment] 2017-02-06 12:29
Dupe of #214

**Closed by nwoolls** 2017-02-06 12:29 UTC
