### ISSUE TITLE
Unhandled Exception 

### ISSUE THREAD

**Issue by shtse8** [nwoolls/MultiMiner#276] opened 2017-08-25 10:14 UTC
```
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 MultiMiner.UX.ViewModels.ApplicationViewModel.ShowCoinChangeNotification() 位置 c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:行号 2561
   在 MultiMiner.UX.ViewModels.ApplicationViewModel.StartMiningLocally() 位置 c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:行号 2094
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.2103.2 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.2104.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
MultiMiner.Remoting
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
MultiMiner.CoinWarz
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.CoinChoose
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.CoinChoose.DLL
----------------------------------------
MultiMiner.WhatMine
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.WhatMine.DLL
----------------------------------------
MultiMiner.WhatToMine
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Newtonsoft.Json
    程序集版本:6.0.0.0
    Win32 版本:6.0.8.18111
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.MultipoolApi
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.MultipoolApi.DLL
----------------------------------------
MultiMiner.NiceHash
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.NiceHash.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MultiMiner.ExchangeApi
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.CSharp
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Core.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2046.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Core.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Services
    程序集版本:4.1.0.363
    Win32 版本:4.1.0.363
    基本代码:file:///C:/Users/Miner/AppData/Local/MultiMiner/MultiMiner.Services.DLL
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.2102.0 built by: NET47REL1LAST
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

```

**Comment by JMLBUSINESS** [comment] 2017-09-05 03:30
Fixed buy downgrading back to 4.0.4

**Comment by nwoolls** [comment] 2017-12-28 21:04
@shtse8 I cannot seem to reproduce this. If this issue is still occurring, can you send the contents of your `%appdata\MultiMiner%` folder to me via email - nwoolls at gmail.com.

**Comment by nwoolls** [comment] 2017-12-29 00:02
Dupe of https://github.com/nwoolls/MultiMiner/issues/283

**Closed by nwoolls** 2017-12-29 00:02 UTC
