### ISSUE TITLE
I can't find a miner

### ISSUE THREAD

**Issue by Devastator12154** [nwoolls/MultiMiner#266] opened 2017-06-02 14:09 UTC
I can see my GPU just fine but for some reason i can't find my Antminer. When i looked for orphaned miners before it worked fine. But it suddenly doesn't work. Any help would be appreciated.

**Comment by nwoolls** [comment] 2017-06-02 16:06
Local USB miner plugged into the PC or a miner on your network?

**Comment by nwoolls** [comment] 2017-06-02 16:07
If this is a local device check the associated wiki page and troubleshooting section:

* https://github.com/nwoolls/MultiMiner/wiki/Local-Devices

**Comment by Devastator12154** [comment] 2017-06-02 17:31
It's a miner on my network

**Comment by nwoolls** [comment] 2017-06-02 20:10
Check the docs here:

* https://github.com/nwoolls/MultiMiner/wiki/Network-Devices

Also try editing your Network Devices config XML to see if you've inadvertently hidden the miner. On *nix it's in `~/.config/MultiMiner/` and on Windows it's `%appdata%\MultiMiner\`.

**Comment by Devastator12154** [comment] 2017-06-02 23:00
I attached an image of the error I'm getting now. But I'm making progress!

**Comment by Devastator12154** [comment] 2017-06-03 16:12
![error pic](https://cloud.githubusercontent.com/assets/29146713/26755168/8a82f83a-484d-11e7-8809-fb4853520baf.jpg)
this is my current error now that i got it communicating

**Comment by iLuvLinux** [comment] 2017-12-03 18:25
Have you installed the driver? 

https://github.com/nwoolls/MultiMiner/#drivers

**Comment by nwoolls** [comment] 2018-01-03 04:55
@Devastator12154 if it's a miner on your network there is no need to click *Start* - what you've done is tried to start mining with your local GPU. Options for the network device are found in its context menu.

If you do in fact want to try to mine with your GPU you can troubleshoot that error by using the *Process Log* context menu to launch the failed miner process in the backend miner directly. That will display more information about the issue, but the issue is likely with your hardware, GPU driver, or backend miner.

* See: https://github.com/nwoolls/MultiMiner/wiki/Process-Log

**Comment by Devastator12154** [comment] 2018-01-03 13:35
Got it. Thanks

**Comment by nwoolls** [comment] 2018-01-09 18:12
Closing as this seems resolved - please reopen if the issue persists.

**Closed by nwoolls** 2018-01-09 18:12 UTC
